{
  "type": "record",
  "name": "Issue",
  "namespace": "com.atlassian.jira.rest.client.api.domain",
  "fields": [
    {
      "name": "timeTracking",
      "type": {
        "type": "record",
        "name": "TimeTracking",
        "fields": [
          {
            "name": "remainingEstimateMinutes",
            "type": "int"
          },
          {
            "name": "originalEstimateMinutes",
            "type": "int"
          },
          {
            "name": "timeSpentMinutes",
            "type": "int"
          }
        ]
      }
    },
    {
      "name": "project",
      "type": {
        "type": "record",
        "name": "BasicProject",
        "fields": [
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "id",
            "type": "long"
          },
          {
            "name": "key",
            "type": "string"
          }
        ]
      }
    },
    {
      "name": "fixVersions",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Collection"
      }
    },
    {
      "name": "resolution",
      "type": {
        "type": "record",
        "name": "Resolution",
        "fields": [
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "description",
            "type": "string"
          },
          {
            "name": "id",
            "type": "long"
          }
        ]
      }
    },
    {
      "name": "expandos",
      "type": {
        "type": "record",
        "name": "Iterable",
        "namespace": "java.lang",
        "fields": []
      }
    },
    {
      "name": "issueLinks",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Collection"
      }
    },
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "changelog",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Collection"
      }
    },
    {
      "name": "priority",
      "type": {
        "type": "record",
        "name": "BasicPriority",
        "fields": [
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "id",
            "type": "long"
          }
        ]
      }
    },
    {
      "name": "labels",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Set"
      }
    },
    {
      "name": "issueType",
      "type": {
        "type": "record",
        "name": "IssueType",
        "fields": [
          {
            "name": "description",
            "type": "string"
          },
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "id",
            "type": "long"
          },
          {
            "name": "isSubtask",
            "type": "boolean"
          }
        ]
      }
    },
    {
      "name": "assignee",
      "type": {
        "type": "record",
        "name": "User",
        "fields": [
          {
            "name": "displayName",
            "type": "string"
          },
          {
            "name": "timezone",
            "type": "string"
          },
          {
            "name": "active",
            "type": "boolean"
          },
          {
            "name": "accountId",
            "type": "string"
          },
          {
            "name": "emailAddress",
            "type": "string"
          },
          {
            "name": "name",
            "type": "string"
          }
        ]
      }
    },
    {
      "name": "status",
      "type": {
        "type": "record",
        "name": "Status",
        "fields": [
          {
            "name": "description",
            "type": "string"
          },
          {
            "name": "statusCategory",
            "type": {
              "type": "record",
              "name": "StatusCategory",
              "fields": [
                {
                  "name": "colorName",
                  "type": "string"
                },
                {
                  "name": "name",
                  "type": "string"
                },
                {
                  "name": "id",
                  "type": "long"
                },
                {
                  "name": "key",
                  "type": "string"
                }
              ]
            }
          },
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "id",
            "type": "long"
          }
        ]
      }
    },
    {
      "name": "issueFields",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Collection"
      }
    },
    {
      "name": "components",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Collection"
      }
    },
    {
      "name": "attachments",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Collection"
      }
    },
    {
      "name": "description",
      "type": "string"
    },
    {
      "name": "watchers",
      "type": {
        "type": "record",
        "name": "BasicWatchers",
        "fields": [
          {
            "name": "isWatching",
            "type": "boolean"
          },
          {
            "name": "numWatchers",
            "type": "int"
          }
        ]
      }
    },
    {
      "name": "operations",
      "type": {
        "type": "record",
        "name": "Operations",
        "fields": [
          {
            "name": "linkGroups",
            "type": "java.lang.Iterable"
          }
        ]
      }
    },
    {
      "name": "key",
      "type": "string"
    },
    {
      "name": "worklogs",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Collection"
      }
    },
    {
      "name": "summary",
      "type": "string"
    },
    {
      "name": "comments",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Collection"
      }
    },
    {
      "name": "subtasks",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Collection"
      }
    },
    {
      "name": "reporter",
      "type": "User"
    },
    {
      "name": "votes",
      "type": {
        "type": "record",
        "name": "BasicVotes",
        "fields": [
          {
            "name": "hasVoted",
            "type": "boolean"
          },
          {
            "name": "votes",
            "type": "int"
          }
        ]
      }
    },
    {
      "name": "affectedVersions",
      "type": {
        "type": "array",
        "items": "string",
        "java-class": "java.util.Collection"
      }
    }
  ]
}