apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio-mc.fullname" . }}
  labels:
    {{- include "minio-mc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio-mc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "minio-mc.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          volumeMounts:
            - name: mc
              mountPath: /.mc
      volumes:
        - name: mc
          emptyDir: {}