bases:
  - "helmfile/bases/helmDefaults.yaml"
  - "helmfile/bases/environments.yaml"

helmfiles:
  - "helmfile/releases/00-bootstrap/helmfile.yaml"
  - "helmfile/releases/10-mino/helmfile.yaml"
  - "helmfile/releases/20-kafka/helmfile.yaml"
  - "helmfile/releases/30-schema-registry/helmfile.yaml"
  - "helmfile/releases/40-atlas/helmfile.yaml"
  - "helmfile/releases/50-amundsen/helmfile.yaml"
  - "helmfile/releases/60-influxdb/helmfile.yaml"
  - "helmfile/releases/70-backstage/helmfile.yaml"
  - "helmfile/releases/80-sources/helmfile.yaml"
  - "helmfile/releases/90-pipelines/helmfile.yaml"
  - "helmfile/releases/100-sinks/helmfile.yaml"

missingFileHandler: Error
