repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: influxdata
    url: https://helm.influxdata.com
  - name: kafka-ui
    url: https://provectus.github.io/kafka-ui
  - name: spark-operator
    url: https://googlecloudplatform.github.io/spark-on-k8s-operator
  - name: gradiant
    url: https://gradiant.github.io/charts
  - name: strimzi
    url: https://strimzi.io/charts
  - name: microcks
    url: https://microcks.io/helm

releases:

  # operators
  - name: kafka-operator
    namespace: sixsense-dev
    chart: strimzi/strimzi-kafka-operator
    version: 0.24.0
    wait: true
    values:
      - helmfile/values/dev/kafka-operator/values.yaml

  - name: spark-operator
    namespace: sixsense-dev
    chart: spark-operator/spark-operator
    version: 1.1.3
    wait: true
    values:
      - helmfile/values/dev/spark-operator/values.yaml

  #  minio
  - name: minio
    namespace: sixsense-dev
    chart: bitnami/minio
    version: 7.1.0
    wait: true
    values:
      - helmfile/values/dev/minio/values.yaml

  # kafka
  - name: kafka
    namespace: sixsense-dev
    chart: charts/kafka
    version: 0.1.0
    needs:
      - sixsense-dev/kafka-operator
    wait: true
    values:
      - helmfile/values/dev/kafka/values.yaml

  - name: kafka-connect
    namespace: sixsense-dev
    chart: charts/kafka-connect
    version: 0.1.0
    needs:
      - sixsense-dev/kafka
    wait: true
    values:
      - helmfile/values/dev/kafka-connect/values.yaml

  - name: base-infra-check
    namespace: sixsense-dev
    chart: charts/base-infra-check
    version: 0.0.1
    needs:
      - sixsense-dev/kafka-connect
    wait: true
    values:
      - helmfile/values/dev/base-infra-check/values.yaml

  - name: kafka-connector
    namespace: sixsense-dev
    chart: charts/kafka-connector
    version: 0.1.0
    wait: true
    values:
      - helmfile/values/dev/kafka-connector/values.yaml

  - name: kafka-ui
    namespace: sixsense-dev
    chart: kafka-ui/kafka-ui
    version: 0.0.1
    values:
      - helmfile/values/dev/kafka-ui/values.yaml

  # apicurio-registry
  - name: apicurio-registry
    namespace: sixsense-dev
    chart: charts/apicurio-registry
    version: 1.2.3
    needs:
      - sixsense-dev/kafka-connect
      - sixsense-dev/base-infra-check
    wait: true
    timeout: 600
    values:
      - helmfile/values/dev/apicurio-registry/values.yaml

  # atlas
  - name: atlas
    namespace: sixsense-dev
    chart: charts/atlas
    version: 0.1.0
    needs:
      - sixsense-dev/kafka
      - sixsense-dev/base-infra-check
    wait: true
    timeout: 600
    values:
      - helmfile/values/dev/atlas/values.yaml

  # amundsen
  - name: amundsen
    namespace: sixsense-dev
    chart: charts/amundsen
    version: 2.1.0
    needs:
      - sixsense-dev/atlas
    wait: true
    values:
      - helmfile/values/dev/amundsen/values.yaml

  #  microcks
  - name: microcks
    namespace: sixsense-dev
    chart: microcks/microcks
    version: 1.3.0
    needs:
      - sixsense-dev/kafka-connect
      - sixsense-dev/apicurio-registry
    values:
      - helmfile/values/dev/microcks/values.yaml

  #  pipelines
  - name: spark-job-jira
    namespace: sixsense-dev
    chart: ../packages/spark-job-jira/.helm
    version: 0.1.0
    wait: true
    needs:
      - sixsense-dev/kafka-connector
      - sixsense-dev/base-infra-check
      - sixsense-dev/apicurio-registry
      - sixsense-dev/influxdb
      - sixsense-dev/minio
    values:
      - helmfile/values/dev/spark-job-jira/values.yaml

  #  influx
  - name: influxdb
    namespace: sixsense-dev
    chart: bitnami/influxdb
    version: 2.2.9
    wait: true
    values:
      - helmfile/values/dev/influxdb/values.yaml

  - name: telegraf
    namespace: sixsense-dev
    chart: charts/telegraf
    version: 1.8.4
    needs:
      - sixsense-dev/influxdb
      - sixsense-dev/spark-job-jira
    values:
      - helmfile/values/dev/telegraf/values.yaml

  # backstage
  - name: backstage
    namespace: sixsense-dev
    chart: charts/backstage
    version: 0.0.0
    values:
      - helmfile/values/dev/backstage/values.yaml