cassandra:
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false

solr:
  zookeeper:
    enabled: false
  externalZookeeper:
    servers: sixsense-zookeeper-client:2181
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false