image:
  repository: tomassatka/k8s-atlas
  tag: 0.2.3

kafka:
  url: sixsense-kafka-bootstrap:9092

embedded:
  hbase: true
  solr: false
  zookeeper: false

zookeeper:
  securityContext:
    enabled: false

elasticsearch:
  master:
    securityContext:
      enabled: false
  coordinating:
    securityContext:
      enabled: false
  data:
    securityContext:
      enabled: false
  ingest:
    securityContext:
      enabled: false