---
bases:
  - "../../bases/helmDefaults.yaml"
  - "../../bases/environments.yaml"

---
releases:
  - name: atlas
    namespace: sixsense-dev
    chart: ../../../charts/atlas
    version: 0.1.0
    timeout: 600
    labels:
      bootstrap: false
      tier: common
    values:
      - values.yaml.gotmpl