spline.mode=REQUIRED
spline.lineageDispatcher=kafka
spline.lineageDispatcher.kafka.topic=ATLAS_HOOK
spline.lineageDispatcher.kafka.producer.bootstrap.servers=sixsense-kafka-bootstrap:9092
spline.lineageDispatcher.kafka.className=za.co.absa.spline.harvester.dispatcher.KafkaLineageDispatcher
spline.lineageDispatcher.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spline.lineageDispatcher.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer
