image: quay.io/microcks/microcks:latest

microcks:
  url: microcks.192.168.210.223.nip.io

keycloak:
  url: keycloak.192.168.210.223.nip.io

features:
  async:
    enabled: true
    defaultBinding: KAFKA
    defaultFrequency: 30
    defaultAvroEncoding: REGISTRY
    kafka:
      install: false
      url: sixsense-kafka-bootstrap:9092
      schemaRegistry:
        url: http://apicurio-registry-apicurio-registry:8080/apis/ccompat/v6
        confluent: true