#temporary disabled till PR merged: https://github.com/influxdata/helm-charts/pull/327
#envFromSecret: "influxdb"

rbac:
  create: false

serviceAccount:
  create: false

service:
  enabled: false

env:
  - name: INFLUX_TOKEN
    valueFrom:
      secretKeyRef:
        name: influxdb
        key: admin-user-token

config:
  outputs:
    - influxdb_v2:
        urls:
          - "http://influxdb:8086"
        token: "${INFLUX_TOKEN}"
        organization: primary
        bucket: primary
  inputs:
    - kafka_consumer:
        brokers: ["sixsense-kafka-bootstrap:9092"]
        topics: ["JiraIssues-0.1.0-master-jira-issues"]
        max_message_len: 1000000
        data_format: "json"
pdb:
  create: false
