#temporary disabled till PR merged: https://github.com/influxdata/helm-charts/pull/327
#envFromSecret: "influxdb"

rbac:
  create: false

serviceAccount:
  create: false

service:
  enabled: false

config:
  outputs:
    - influxdb:
        urls:
          - "http://influxdb:8086"
        database: "jira"
        username: "admin"
        password: $admin-user-password
  inputs:
    - kafka_consumer:
        brokers: ["kafka:9092"]
        topics: ["oslc-topic-changerequests"]
        max_message_len: 1000000
        data_format: "json"
pdb:
  create: false
