---
bases:
  - "../../bases/helmDefaults.yaml"
  - "../../bases/environments.yaml"

---
releases:
  - name: spark-job-jira-atlas
    namespace: sixsense-dev
    chart: ../../../packages/spark-job-jira-atlas/.helm
    version: 0.1.0
    labels:
      bootstrap: false
      tier: app
    values:
      - values.yaml.gotmpl