apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-job-jira-source
  namespace: sixsense-dev
spec:
  type: Java
  mode: cluster
  image: {{.Values.image.repository}}
  imagePullPolicy: {{.Values.image.pullPolicy}}
  mainClass: com.sixgroup.sixsense.pipeline.jira.issue.JiraIssuesKafkaSource
  mainApplicationFile: "local:///jobs/spark-job-jira.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: checkpoint
      emptyDir: {}
  sparkConf:
    "spark.extraListeners": "com.hortonworks.spark.atlas.SparkAtlasEventTracker"
    "spark.sql.queryExecutionListeners": "com.hortonworks.spark.atlas.SparkAtlasEventTracker"
    "spark.sql.streaming.streamingQueryListeners": "com.hortonworks.spark.atlas.SparkAtlasStreamingQueryEventTracker"
    "spark.driver.extraJavaOptions": "-Datlas.conf=/atlas/conf/"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    envVars:
      MINIO_ENDPOINT: {{ .Values.driver.env.MINIO_ENDPOINT }}
      MINIO_BUCKET: {{ .Values.driver.env.MINIO_BUCKET }}
      SCHEMA_REGISTRY_URL: {{ .Values.driver.env.SCHEMA_REGISTRY_URL }}
      KAFKA_BOOTSTRAP_SERVER: {{ .Values.driver.env.KAFKA_BOOTSTRAP_SERVER }}
      KAFKA_TOPIC_SOURCE_JIRA_ISSUES: {{ .Values.driver.env.KAFKA_TOPIC_SOURCE_JIRA_ISSUES }}
      KAFKA_GROUP_ID: {{ .Values.driver.env.KAFKA_GROUP_ID}}
      SPARK_CHECKPOINT_LOCATION: {{ .Values.driver.env.SPARK_CHECKPOINT_LOCATION }}
      DELTA_TABLE_JIRA_ISSUE: {{ .Values.driver.env.DELTA_TABLE_JIRA_ISSUE }}
    envSecretKeyRefs:
      MINIO_ACCESS_KEY:
        name: minio
        key: access-key
      MINIO_SECRET_KEY:
        name: minio
        key: secret-key
    volumeMounts:
      - name: minio
        mountPath: /checkpoint
#TODO to enable custom configmap mutating admission webhook is needed to use this feature https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#about-the-mutating-admission-webhook
    configMaps:
      - name: spark-atlas-config
        path: /atlas/conf/atlas-application.properties
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
---

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-job-jira-sink
  namespace: sixsense-dev
spec:
  type: Java
  mode: cluster
  image: {{.Values.image.repository}}
  imagePullPolicy: {{.Values.image.pullPolicy}}
  mainClass: com.sixgroup.sixsense.pipeline.jira.issue.JiraIssuesWasteKafkaSink
  mainApplicationFile: "local:///jobs/spark-job-jira.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: checkpoint
      emptyDir: {}
  sparkConf:
    "spark.extraListeners": "com.hortonworks.spark.atlas.SparkAtlasEventTracker"
    "spark.sql.queryExecutionListeners": "com.hortonworks.spark.atlas.SparkAtlasEventTracker"
    "spark.sql.streaming.streamingQueryListeners": "com.hortonworks.spark.atlas.SparkAtlasStreamingQueryEventTracker"
    "spark.driver.extraJavaOptions": "-Datlas.conf=/atlas/conf/"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    envVars:
      MINIO_ENDPOINT: {{ .Values.driver.env.MINIO_ENDPOINT }}
      MINIO_BUCKET: {{ .Values.driver.env.MINIO_BUCKET }}
      SCHEMA_REGISTRY_URL: {{ .Values.driver.env.SCHEMA_REGISTRY_URL }}
      KAFKA_BOOTSTRAP_SERVER: {{ .Values.driver.env.KAFKA_BOOTSTRAP_SERVER }}
      KAFKA_TOPIC_JIRA_ISSUES: {{ .Values.driver.env.KAFKA_TOPIC_JIRA_ISSUES }}
      KAFKA_GROUP_ID: {{ .Values.driver.env.KAFKA_GROUP_ID}}
      SPARK_CHECKPOINT_LOCATION: {{ .Values.driver.env.SPARK_CHECKPOINT_LOCATION }}
      DELTA_TABLE_JIRA_ISSUE: {{ .Values.driver.env.DELTA_TABLE_JIRA_ISSUE }}
    envSecretKeyRefs:
      MINIO_ACCESS_KEY:
        name: minio
        key: access-key
      MINIO_SECRET_KEY:
        name: minio
        key: secret-key
    volumeMounts:
      - name: minio
        mountPath: /checkpoint
#TODO to enable custom configmap mutating admission webhook is needed to use this feature https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#about-the-mutating-admission-webhook
    configMaps:
      - name: spark-atlas-config
        path: /atlas/conf/atlas-application.properties
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1