apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schema-load.fullname" $ }}
  labels:
    {{- include "schema-load.labels" $ | nindent 4 }}
data:
  {{- ($.Files.Glob "avro/*").AsConfig | nindent 4 }}