oidc:
  enabled: false
neo4j:
  enabled: false

metadata:
  proxy:
    host: atlas-atlas
    port: 21000
    user: admin
    password: admin

search:
  proxy:
    endpoint: amundsen-elasticsearch-master:9200

elasticsearch:
  enabled: false
  sysctlImage:
    enabled: false
  master:
    securityContext:
      enabled: false
  coordinating:
    securityContext:
      enabled: false
  data:
    securityContext:
      enabled: false
  ingest:
    securityContext:
      enabled: false

cron:
  image:
    name: tomassatka/amundsen-atlas-extractor
    tag: 0.0.2
  schedule: '"* * * * *"'
  env:
    - name: ATLAS_URL
      value: atlas-atlas
    - name: ATLAS_PORT
      value: 21000
    - name: ATLAS_USERNAME
      value: admin
    - name: ATLAS_PASSWORD
      value: admin
    - name: ELASTICSEARCH_HOST
      value: amundsen-elasticsearch-master
