name=jira-source
tasks.max=1
connector.class=io.confluent.connect.jira.JiraSourceConnector
confluent.topic.bootstrap.servers=localhost:9092
confluent.topic.replication.factor=1

topic.name.pattern=jira-topic-${entityName}
#jira.tables=changelogs,issue_comments,issues,project_categories,project_types,projects,resolutions,roles,users,versions,worklogs
jira.tables=issues
jira.url=https://six-group.atlassian.net
jira.username=jose.badeau@gmail.com
jira.api.token=e8g5AoUdFXOoXKj1eTPbD216
jira.since=2021-01-01 10:00
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081

errors.log.enable=true
errors.log.include.messages=true

#ignore wrong data insertion
errors.tolerance = all

