repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: influxdata
    url: https://helm.influxdata.com
  - name: kafka-ui
    url: https://provectus.github.io/kafka-ui
  - name: spark-operator
    url: https://googlecloudplatform.github.io/spark-on-k8s-operator

releases:

  - name: atlas
    namespace: sixsense-dev
    chart: ../charts/atlas
    version: 0.1.0
#    wait: true
    values:
      - values/dev/atlas/values.yaml

