repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: influxdata
    url: https://helm.influxdata.com
  - name: kafka-ui
    url: https://provectus.github.io/kafka-ui
  - name: spark-operator
    url: https://googlecloudplatform.github.io/spark-on-k8s-operator
  - name: gradiant
    url: https://gradiant.github.io/charts
  - name: strimzi
    url: https://strimzi.io/charts
  - name: microcks
    url: https://microcks.io/helm

releases:

  #  pipelines
  - name: spark-job-jira
    namespace: sixsense-dev
    chart: ../modules/spark-job-jira/.helm
    version: 0.1.0
    wait: true
    needs:
      - sixsense-dev/kafka-connector
      - sixsense-dev/base-infra-check
      - sixsense-dev/apicurio-registry
      - sixsense-dev/influxdb
      - sixsense-dev/minio
    values:
      - values/dev/spark-job-jira/values.yaml
