apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jira-issues-connector
  labels:
    strimzi.io/cluster: {{ .Values.cluster }}
spec:
  class: {{ .Values.jira.class }}
  tasksMax: {{ .Values.jira.tasksMax }}
  config:
    connector.class: {{ .Values.class }}
    tasks.max: 1
    http.offset.initial: {{ .Values.jira.offset.initial }}
    http.request.url: {{ .Values.jira.url }}
    http.request.headers: "Accept: application/json"
    http.request.params: {{ .Values.jira.jql }}
    http.auth.type: Basic
    http.auth.user: {{ .Values.jira.user }}
    http.auth.password: {{ .Values.jira.apiToken }}
    http.response.list.pointer: /issues
    http.response.record.offset.pointer: key=/id, timestamp=/fields/updated
    http.timer.interval.millis: 30000
    http.timer.catchup.interval.millis: 1000
    kafka.topic: {{ .Values.jira.topic }}