<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.confluent</groupId>
    <artifactId>kafka-connect-jira</artifactId>
    <name>kafka-connect-jira</name>
    <version>1.0.5</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.inceptionYear>2019</project.inceptionYear>
        <license.current.year>2019</license.current.year>
        <connect-runtime-version>2.0.0</connect-runtime-version>
        <confluent.hub.packaging.version>0.11.1</confluent.hub.packaging.version>
        <confluent.licencing.version>0.11.1</confluent.licencing.version>
        <confluent.connect.plugins.common.version>${project.parent.version}</confluent.connect.plugins.common.version>
        <confluent.connect.common.utils.version>0.3.1</confluent.connect.common.utils.version>
        <confluent.connect.parent.operation.version>1.0.11</confluent.connect.parent.operation.version>
        <spring.beans.version>5.3.1</spring.beans.version>
        <skipIntegrationTests>true</skipIntegrationTests>
    </properties>

    <repositories>
        <repository>
            <id>confluent</id>
            <name>Confluent</name>
            <url>https://packages.confluent.io/maven/</url>
        </repository>
        <repository>
            <id>atlassian-public</id>
            <url>https://maven.atlassian.com/repository/public</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
                <checksumPolicy>warn</checksumPolicy>
            </snapshots>
            <releases>
                <enabled>true</enabled>
                <checksumPolicy>warn</checksumPolicy>
            </releases>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <finalName>confluentinc-${project.artifactId}-${project.version}-preview</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                    <descriptors>
                        <descriptor>${project.basedir}/src/main/assembly/assembly.xml</descriptor>
                    </descriptors>
                </configuration>
                <executions>
                    <execution>
                        <id>plugin</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.6</version>
        </dependency>
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>connect-operation-core</artifactId>
            <version>${confluent.connect.parent.operation.version}</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/image/lib/connect-operation-core-1.0.11.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>connect-operation-http</artifactId>
            <version>${confluent.connect.parent.operation.version}</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/image/lib/connect-operation-http-1.0.11.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>connect-operation-rest</artifactId>
            <version>${confluent.connect.parent.operation.version}</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/image/lib/connect-operation-rest-1.0.11.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>connect-utils</artifactId>
            <version>${confluent.connect.common.utils.version}</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/image/lib/connect-utils-0.3.1.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>connect-api</artifactId>
            <version>2.8.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.10.5</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.10.5</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.10.5.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>2.8.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>${spring.beans.version}</version>
        </dependency>
        <dependency>
            <groupId>com.atlassian.jira</groupId>
            <artifactId>jira-rest-java-client-core</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>javax.ws.rs</groupId>
                    <artifactId>jsr311-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.codehaus.jackson</groupId>
                    <artifactId>jackson-mapper-asl</artifactId>
                </exclusion>
            </exclusions>
            <version>5.2.2</version>
        </dependency>
        <dependency>
            <groupId>io.atlassian.fugue</groupId>
            <artifactId>fugue</artifactId>
            <version>4.7.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.mashape.unirest</groupId>
            <artifactId>unirest-java</artifactId>
            <version>1.4.9</version>
        </dependency>
    </dependencies>

</project>