apiVersion: v1
appVersion: 5.0.1
description: Chart dedicated to upload avro schemas to confluent schema registry
icon: https://www.confluent.io/wp-content/themes/confluent/assets/images/confluent-logo-300.png
keywords:
  - confluent
  - kafka
  - schema-registry
name: schema-uploader
version: 1.2.3
