image:
  repository: tomassatka/spark-job-jira
  pullPolicy: IfNotPresent
  tag: 0.0.23
mainClass: com.sixgroup.sixsense.jira.oslc.JiraIssueToOslcChangeRequest
driver:
  env:
    KAFKA_JIRA_ISSUE_TOPIC: 'jira-topic-issues'
    KAFKA_OSLC_CHANGE_REQUEST_TOPIC: 'oslc-topic-changerequests'
    KAFKA_GROUP_ID: 'jira'
    BOOTSTRAP_SERVER: 'kafka:9092'
    CHECKPOINT_LOCATION: '/checkpoint'
    SCHEMA_REGISTRY_URL: 'http://cp-schema-registry:8081'