name: Build

on:
  push:
    branches-ignore:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      ##################################################################################################################
      # Clone
      ##################################################################################################################
      - name: Clone
        uses: actions/checkout@v2

      ##################################################################################################################
      # Setup
      ##################################################################################################################
      - name: Setup - certificates
        if: ${{ env.ACT }}
        run: apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

      - name: Setup - JavaScript
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup - Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Workaround until Act fix
      - name: Setup - Maven
        if: ${{ env.ACT }}
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.2

      ##################################################################################################################
      # Restore Cache
      ##################################################################################################################
      - name: Cache - Yarn
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Cache - Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      ##################################################################################################################
      # Env
      ##################################################################################################################
      - name: Env - VERSION
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      ##################################################################################################################
      # Build JavaScript
      ##################################################################################################################
      - name: Yarn - install
        run: yarn

      - name: Yarn - compile
        run: yarn tsc

      - name: Yarn - build
        run: yarn build

      ##################################################################################################################
      # Maven
      ##################################################################################################################
      - name: Maven - package
        run: mvn package

      ##################################################################################################################
      # Docker
      ##################################################################################################################
      - name: Docker - login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker - build & push backstage-frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./packages/app/Dockerfile
          push: true
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_REPO }}/backstage-frontend
          tags: ${{env.VERSION}},latest
          tag_with_ref: true
          add_git_labels: true

      - name: Docker - build & push backstage-backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./packages/backend/Dockerfile
          push: true
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_REPO }}/backstage-backend
          tags: ${{env.VERSION}},latest
          tag_with_ref: true
          add_git_labels: true

      - name: Docker - build & push kafka-connect
        uses: docker/build-push-action@v2
        with:
          path: ./packages/kafka-connect
          push: true
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_REPO }}/kafka-connect
          tags: ${{env.VERSION}},latest
          tag_with_ref: true
          add_git_labels: true

      - name: Docker - build & push spark-job-jira
        uses: docker/build-push-action@v2
        with:
          path: ./packages/spark-job-jira
          push: true
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_REPO }}/spark-job-jira
          tags: ${{env.VERSION}},latest
          tag_with_ref: true
          add_git_labels: true

      ##################################################################################################################
      # OpenShift
      ##################################################################################################################
      - name: OpenShift - Install CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest

      - name: OpenShift - Set context
        uses: redhat-actions/oc-login@v1
        if: ${{ env.ACT }}
        with:
          openshift_server_url: https://api.crc.testing:6443
          openshift_username: ${{ secrets.OPENSHIFT_USERNAME }}
          openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
          insecure_skip_tls_verify: true

      ##################################################################################################################
      # Helmfile
      ##################################################################################################################
      - name: Helmfile - installl
        uses: mamezou-tech/setup-helmfile@v0.8.0
        if: ${{ env.ACT }}

      - name: Helmfile - sync
        if: ${{ env.ACT }}
        run: helmfile sync