name: Build

on:
  push:
    branches-ignore:
      - master

jobs:

  build-java:
    runs-on: ubuntu-latest
    steps:

      - name: Clone
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup JavaScript
        uses: actions/setup-node@v2
        with:
          node_version: '14'

      - name: Restore Java cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Restore JavaScript Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      name: Yarn install
        run: yarn

      name: Yarn TypeScript compile
        run: yarn tsc

      name: Yarn build
        run: yarn build

      name: Maven build
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }}
        run: mvn package