name: Java Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clone
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: mvn -B package --file pom.xml